stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - source_data/medical_insurance.csv

    outs:
    - data/raw/medical_insurance.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/medical_insurance.csv

    outs:
    - data/processed/train_medical_insurance.csv
    - data/processed/test_medical_insurance.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_medical_insurance.csv
    - data/processed/test_medical_insurance.csv
    - src/train_and_evaluate.py

    params: 
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio

    # metrics:
    # - reports/scores.json
    #   cache: false
    # - reports/params.json
    #   cache: false

    # outs:
    # - models/model.joblib

  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml

    deps:
      - src/log_production_model.py



